"""Build mps.json from scraped MP data, matched to bees/ image folder."""
import json
import os

# Scraped MP data (one entry per MP, in alphabetical order by surname slug)
MPS = [
    {"name": "Steve Abel", "slug": "abel-steve", "party": "Green", "electorate": "List", "parliament_email": "Steve.Abel@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/steve_abel", "facebook": "https://www.facebook.com/SteveAbelGreens", "twitter": "https://twitter.com/abelsteve", "instagram": "https://www.instagram.com/steveabelthereal", "tiktok": None, "youtube": None},
    {"name": "Hon Ginny Andersen", "slug": "andersen-ginny", "party": "Labour", "electorate": "List", "parliament_email": "Virginia.Andersen@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/ginny-andersen/", "facebook": "https://www.facebook.com/GinnyAndersenHuttSouth", "twitter": "https://twitter.com/ginnyandersen", "instagram": "https://www.instagram.com/ginny_andersen/", "tiktok": None, "youtube": None},
    {"name": "Miles Anderson", "slug": "anderson-miles", "party": "National", "electorate": "Waitaki", "parliament_email": "Miles.Anderson@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/milesanderson", "facebook": "https://www.facebook.com/MilesAndersonWaitaki", "twitter": None, "instagram": "https://www.instagram.com/milesandersonforwaitaki", "tiktok": None, "youtube": None},
    {"name": "Jamie Arbuckle", "slug": "arbuckle-jamie", "party": "NZ First", "electorate": "List", "parliament_email": "Jamie.Arbuckle@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.nzfirst.nz/jamie_arbuckle", "facebook": "https://www.facebook.com/jamiearbuckle.nzfirst", "twitter": None, "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Carl Bates", "slug": "bates-carl", "party": "National", "electorate": "Whanganui", "parliament_email": "Carl.Bates@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/carlbates", "facebook": "https://www.facebook.com/CarlBatesWhanganui", "twitter": "https://twitter.com/CarlBates", "instagram": "https://www.instagram.com/carlbateswhanganui", "tiktok": None, "youtube": None},
    {"name": "Hon Andrew Bayly", "slug": "bayly-andrew", "party": "National", "electorate": "Port Waikato", "parliament_email": "Andrew.Bayly@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://andrewbayly.national.org.nz", "facebook": "https://facebook.com/AndrewBaylyMP/", "twitter": "https://twitter.com/bayly_andrew", "instagram": "https://instagram.com/andrewbaylymp/", "tiktok": None, "youtube": None},
    {"name": "Camilla Belich", "slug": "belich-camilla", "party": "Labour", "electorate": "List", "parliament_email": "Camilla.Belich@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://labour.org.nz/our-team/camilla-belich/", "facebook": "https://facebook.com/CamillaBelichLabour/", "twitter": "https://twitter.com/Camilla_Belich", "instagram": "https://instagram.com/camilla_belich_mp", "tiktok": None, "youtube": None},
    {"name": "Glen Bennett", "slug": "bennett-glen", "party": "Labour", "electorate": "List", "parliament_email": "Glen.Bennett@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://labour.org.nz/our-team/glen-bennett/", "facebook": "https://facebook.com/glenbennettlabour", "twitter": None, "instagram": "https://instagram.com/glen.bennettmp/", "tiktok": None, "youtube": None},
    {"name": "Dan Bidois", "slug": "bidois-dan", "party": "National", "electorate": "Northcote", "parliament_email": "Dan.Bidois@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/danbidois", "facebook": "https://www.facebook.com/DanBidoisMP", "twitter": "https://twitter.com/dan_bidois", "instagram": "https://www.instagram.com/danbidoismp", "tiktok": None, "youtube": None},
    {"name": "Hon Chris Bishop", "slug": "bishop-chris", "party": "National", "electorate": "Hutt South", "parliament_email": "Chris.Bishop@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://chrisbishop.national.org.nz", "facebook": "https://facebook.com/chrisbishopmp", "twitter": "https://twitter.com/cjsbishop", "instagram": "https://instagram.com/cjsbishop/", "tiktok": None, "youtube": None},
    {"name": "Rachel Boyack", "slug": "boyack-rachel", "party": "Labour", "electorate": "Nelson", "parliament_email": "Rachel.Boyack@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://labour.org.nz/our-team/rachel-boyack/", "facebook": "https://facebook.com/RachelBoyackNelson/", "twitter": "https://twitter.com/rachelboyack", "instagram": "https://instagram.com/rachelboyack/", "tiktok": None, "youtube": None},
    {"name": "Hon Cameron Brewer", "slug": "brewer-cameron", "party": "National", "electorate": "Upper Harbour", "parliament_email": "Cameron.Brewer@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://national.org.nz/cameronbrewer", "facebook": "https://facebook.com/CameronBrewerUpperHarbour", "twitter": None, "instagram": "https://instagram.com/cameronbrewernz/", "tiktok": None, "youtube": None},
    {"name": "Hon Rachel Brooking", "slug": "brooking-rachel", "party": "Labour", "electorate": "Dunedin", "parliament_email": "Rachel.Brooking@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/rachel-brooking/", "facebook": "https://www.facebook.com/RachelBrookingMP/", "twitter": "https://twitter.com/brookingrachel", "instagram": "https://www.instagram.com/Rachelbrookingmp", "tiktok": None, "youtube": None},
    {"name": "Hon Simeon Brown", "slug": "brown-simeon", "party": "National", "electorate": "Pakuranga", "parliament_email": "Simeon.Brown@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://simeonbrown.national.org.nz", "facebook": "https://facebook.com/SimeonBrownMP", "twitter": "https://twitter.com/SimeonBrownMP", "instagram": "https://instagram.com/simeonbrownmp/", "tiktok": None, "youtube": None},
    {"name": "Rt Hon Gerry Brownlee", "slug": "brownlee-gerry", "party": "National", "electorate": "List", "parliament_email": "Gerry.Brownlee@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://gerrybrownlee.national.org.nz", "facebook": "https://facebook.com/gerrybrownleemp", "twitter": None, "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Hon Mike Butterick", "slug": "butterick-mike", "party": "National", "electorate": "Wairarapa", "parliament_email": "Mike.Butterick@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/mikebutterick", "facebook": "https://www.facebook.com/nzmikebutterick", "twitter": None, "instagram": "https://www.instagram.com/mikebuttericknat/", "tiktok": None, "youtube": None},
    {"name": "Mark Cameron", "slug": "cameron-mark", "party": "ACT", "electorate": "List", "parliament_email": "Mark.Cameron@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.act.org.nz/mark-cameron", "facebook": "https://facebook.com/MarkCameronACTNZ", "twitter": None, "instagram": "https://instagram.com/markcameronmp/", "tiktok": None, "youtube": None},
    {"name": "Dr Hamish Campbell", "slug": "campbell-hamish", "party": "National", "electorate": "Ilam", "parliament_email": "Hamish.Campbell@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/hamishcampbell", "facebook": "https://www.facebook.com/hamishcampbellforilam", "twitter": None, "instagram": "https://www.instagram.com/hamishcampbellforilam", "tiktok": None, "youtube": None},
    {"name": "Kahurangi Carter", "slug": "carter-kahurangi", "party": "Green", "electorate": "List", "parliament_email": "Kahurangi.Carter@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://greens.org.nz/kahurangi_carter", "facebook": "https://facebook.com/KahuCarter", "twitter": "https://twitter.com/KahurangiMP", "instagram": "https://instagram.com/kahurangicarter", "tiktok": None, "youtube": None},
    {"name": "Dr Carlos Cheung", "slug": "cheung-carlos", "party": "National", "electorate": "Mt Roskill", "parliament_email": "Carlos.Cheung@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/carloscheung", "facebook": "https://www.facebook.com/CarlosCheungMtRoskill", "twitter": None, "instagram": "https://www.instagram.com/carloscheung/", "tiktok": None, "youtube": None},
    {"name": "Hon Karen Chhour", "slug": "chhour-karen", "party": "ACT", "electorate": "List", "parliament_email": "Karen.Chhour@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://act.org.nz/karen-chhour", "facebook": "https://facebook.com/karenchhourACTlistmemberofparliament/", "twitter": None, "instagram": "https://instagram.com/karenchhour/", "tiktok": None, "youtube": None},
    {"name": "Hon Casey Costello", "slug": "costello-casey", "party": "NZ First", "electorate": "List", "parliament_email": "Casey.Costello@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.nzfirst.nz/casey-costello", "facebook": "https://www.facebook.com/caseycostellonzfirst", "twitter": None, "instagram": "https://www.instagram.com/caseycostellomp/", "tiktok": None, "youtube": None},
    {"name": "Tim Costley", "slug": "costley-tim", "party": "National", "electorate": "Ōtaki", "parliament_email": "Tim.CostleyMP@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/timcostley", "facebook": "https://www.facebook.com/timcostleynz", "twitter": None, "instagram": "https://www.instagram.com/timcostleynz/", "tiktok": None, "youtube": None},
    {"name": "Simon Court", "slug": "court-simon", "party": "ACT", "electorate": "List", "parliament_email": "Simon.Court@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.act.org.nz/simon-court", "facebook": "https://www.facebook.com/simoncourtact/", "twitter": "https://twitter.com/SimonCourtACT", "instagram": "https://www.instagram.com/simoncourtact/", "tiktok": None, "youtube": None},
    {"name": "Georgie Dansey", "slug": "dansey-georgie", "party": "Labour", "electorate": "List", "parliament_email": "Georgie.Dansey@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/georgie-dansey/", "facebook": "https://www.facebook.com/georgiedansey", "twitter": None, "instagram": "https://www.instagram.com/georgiedansey", "tiktok": None, "youtube": None},
    {"name": "Hon Marama Davidson", "slug": "davidson-marama", "party": "Green", "electorate": "List", "parliament_email": "Marama.Davidson@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/marama_davidson", "facebook": "https://www.facebook.com/maramadavidsonmp/", "twitter": "https://twitter.com/MaramaDavidson", "instagram": "https://www.instagram.com/maramadavidson/", "tiktok": None, "youtube": None},
    {"name": "Mike Davidson", "slug": "davidson-mike", "party": "Green", "electorate": "List", "parliament_email": "Mike.Davidson@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/mike_davidson", "facebook": "https://www.facebook.com/OtautahiMike", "twitter": None, "instagram": "https://www.instagram.com/otautahimike/", "tiktok": None, "youtube": None},
    {"name": "Reuben Davidson", "slug": "davidson-reuben", "party": "Labour", "electorate": "Christchurch East", "parliament_email": "Reuben.Davidson@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/reuben-davidson/", "facebook": "https://www.facebook.com/ReubenDavidsonLabour", "twitter": None, "instagram": "https://www.instagram.com/reuben4east", "tiktok": None, "youtube": None},
    {"name": "Hon Matt Doocey", "slug": "doocey-matt", "party": "National", "electorate": "Waimakariri", "parliament_email": "Matt.Doocey@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://mattdoocey.national.org.nz/", "facebook": "https://www.facebook.com/MattDoocey.Waimakariri/", "twitter": None, "instagram": "https://www.instagram.com/matt.dooceymp/", "tiktok": None, "youtube": None},
    {"name": "Hon Barbara Edmonds", "slug": "edmonds-barbara", "party": "Labour", "electorate": "Mana", "parliament_email": "Barbara.Edmonds@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/barbara-edmonds/", "facebook": "https://www.facebook.com/BarbaraEdmondsMP/", "twitter": "https://twitter.com/BarbEdmondsMana", "instagram": "https://www.instagram.com/barbara_edmonds_mp_/", "tiktok": None, "youtube": None},
    {"name": "Tākuta Ferris", "slug": "ferris-tākuta", "party": "Independent", "electorate": "Te Tai Tonga", "parliament_email": "Takuta.Ferris@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": None, "facebook": "https://www.facebook.com/takutataitonga", "twitter": None, "instagram": "https://www.instagram.com/takuta_ferris/", "tiktok": None, "youtube": None},
    {"name": "Greg Fleming", "slug": "fleming-greg", "party": "National", "electorate": "Maungakiekie", "parliament_email": "Greg.Fleming@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/gregfleming", "facebook": "https://www.facebook.com/GregFlemingMaungakiekie", "twitter": None, "instagram": "https://www.instagram.com/gflemingnational/", "tiktok": None, "youtube": None},
    {"name": "Andy Foster", "slug": "foster-andy", "party": "NZ First", "electorate": "List", "parliament_email": "Andy.Foster@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.nzfirst.nz/andy-foster", "facebook": "https://www.facebook.com/andyfostermp", "twitter": None, "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Paulo Garcia", "slug": "garcia-paulo", "party": "National", "electorate": "New Lynn", "parliament_email": "Paulo.Garcia@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/paulogarcia", "facebook": "https://www.facebook.com/PauloGarciaMP", "twitter": None, "instagram": "https://www.instagram.com/paulogarcia.mp/", "tiktok": None, "youtube": None},
    {"name": "Hon Julie Anne Genter", "slug": "genter-julie-anne", "party": "Green", "electorate": "Rongotai", "parliament_email": "Julieanne.Genter@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/julie_anne_genter", "facebook": "https://www.facebook.com/JulieAnneGenter", "twitter": "https://twitter.com/julieannegenter", "instagram": "https://www.instagram.com/julieannegenter/", "tiktok": None, "youtube": None},
    {"name": "Hon Paul Goldsmith", "slug": "goldsmith-paul", "party": "National", "electorate": "List", "parliament_email": "Paul.Goldsmith@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://paulgoldsmith.national.org.nz", "facebook": "https://www.facebook.com/paulgoldsmithmp/", "twitter": "https://twitter.com/PaulGoldsmithMP", "instagram": "https://www.instagram.com/paulgoldsmithmp", "tiktok": None, "youtube": None},
    {"name": "Hon Nicola Grigg", "slug": "grigg-nicola", "party": "National", "electorate": "Selwyn", "parliament_email": "Nicola.Grigg@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://nicolagrigg.national.org.nz", "facebook": "https://www.facebook.com/NicolaGriggSelwyn/", "twitter": None, "instagram": "https://www.instagram.com/nicolagriggmp", "tiktok": None, "youtube": None},
    {"name": "Shanan Halbert", "slug": "halbert-shanan", "party": "Labour", "electorate": "List", "parliament_email": "Shanan.Halbert@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/shanan-halbert/", "facebook": "https://www.facebook.com/shananhalbertMP", "twitter": "https://twitter.com/shananhalbert", "instagram": "https://www.instagram.com/shanan.halbert/", "tiktok": None, "youtube": None},
    {"name": "Ryan Hamilton", "slug": "hamilton-ryan", "party": "National", "electorate": "Hamilton East", "parliament_email": "Ryan.Hamilton@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/ryanhamilton", "facebook": "https://www.facebook.com/Hamilton4HamiltonEast", "twitter": None, "instagram": "https://www.instagram.com/hamiltonforhamilton/", "tiktok": None, "youtube": None},
    {"name": "Francisco Hernandez", "slug": "hernandez-francisco", "party": "Green", "electorate": "List", "parliament_email": "Francisco.Hernandez@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz", "facebook": "https://www.facebook.com/FranciscoHernandezforDunedin", "twitter": None, "instagram": "https://www.instagram.com/fran4dunedin", "tiktok": None, "youtube": None},
    {"name": "Rt Hon Chris Hipkins", "slug": "hipkins-chris", "party": "Labour", "electorate": "Remutaka", "parliament_email": "Chris.Hipkins@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/rt-hon-chris-hipkins/", "facebook": "https://www.facebook.com/chrishipkinsmp", "twitter": "https://twitter.com/chrishipkins", "instagram": "https://www.instagram.com/chrishipkinsmp/", "tiktok": None, "youtube": None},
    {"name": "Hon Andrew Hoggard", "slug": "hoggard-andrew", "party": "ACT", "electorate": "List", "parliament_email": "Andrew.Hoggard@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.act.org.nz/andrew-hoggard", "facebook": "https://www.facebook.com/andrewhoggardact", "twitter": None, "instagram": "https://www.instagram.com/andrewhoggardact/", "tiktok": None, "youtube": None},
    {"name": "Hon Willie Jackson", "slug": "jackson-willie", "party": "Labour", "electorate": "List", "parliament_email": "Willie.Jackson@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/willie-jackson/", "facebook": "https://www.facebook.com/WillieJacksonLabour/", "twitter": "https://twitter.com/WillieJLabour", "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Hon Shane Jones", "slug": "jones-shane", "party": "NZ First", "electorate": "List", "parliament_email": "Shane.Jones@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.nzfirst.nz/shane-jones", "facebook": "https://www.facebook.com/ShaneJones.nz", "twitter": "https://twitter.com/mangonui08", "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Oriini Kaipara", "slug": "kaipara-oriini", "party": "Te Pāti Māori", "electorate": "Tāmaki Makaurau", "parliament_email": "Oriini.Kaipara@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.maoriparty.org.nz/oriini_kaipara", "facebook": "https://www.facebook.com/profile.php?id=61578317851789", "twitter": None, "instagram": "https://www.instagram.com/oriini_kaipara/", "tiktok": None, "youtube": None},
    {"name": "Mariameno Kapa-Kingi", "slug": "kapa-kingi-mariameno", "party": "Independent", "electorate": "Te Tai Tokerau", "parliament_email": "Mariameno.Kapa-Kingi@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": None, "facebook": "https://www.facebook.com/KapaKingi", "twitter": None, "instagram": "https://www.instagram.com/mariameno.kapakingi/", "tiktok": None, "youtube": None},
    {"name": "Dana Kirkpatrick", "slug": "kirkpatrick-dana", "party": "National", "electorate": "East Coast", "parliament_email": "Dana.Kirkpatrick@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/danakirkpatrick", "facebook": "https://www.facebook.com/DanaKirkpatrickEastCoast", "twitter": None, "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Barbara Kuriger", "slug": "kuriger-barbara", "party": "National", "electorate": "Taranaki-King Country", "parliament_email": "Barbara.Kuriger@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://barbarakuriger.national.org.nz", "facebook": "https://www.facebook.com/BarbaraKurigerMP", "twitter": "https://twitter.com/BarbaraKuriger", "instagram": "https://www.instagram.com/BarbaraKurigerMP/", "tiktok": None, "youtube": None},
    {"name": "Ingrid Leary", "slug": "leary-ingrid", "party": "Labour", "electorate": "Taieri", "parliament_email": "Ingrid.Leary@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/ingrid-leary/", "facebook": "https://www.facebook.com/IngridLearyMP", "twitter": None, "instagram": "https://www.instagram.com/ingrid.leary/", "tiktok": None, "youtube": None},
    {"name": "Hon Melissa Lee", "slug": "lee-melissa", "party": "National", "electorate": "List", "parliament_email": "Melissa.Lee@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://melissalee.national.org.nz", "facebook": "https://www.facebook.com/mpmelissalee", "twitter": "https://twitter.com/melissaleemp", "instagram": "https://www.instagram.com/melissaleemp", "tiktok": None, "youtube": None},
    {"name": "Nancy Lu", "slug": "lu-nancy", "party": "National", "electorate": "List", "parliament_email": "Nancy.Lu@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/nancylu", "facebook": "https://www.facebook.com/nancylumpnz/", "twitter": None, "instagram": "https://www.instagram.com/nancylu.mp/", "tiktok": None, "youtube": None},
    {"name": "Rt Hon Christopher Luxon", "slug": "luxon-christopher", "party": "National", "electorate": "Botany", "parliament_email": "Christopher.Luxon@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": None, "facebook": "https://www.facebook.com/christopherluxon", "twitter": "https://twitter.com/chrisluxonmp", "instagram": "https://www.instagram.com/christopherluxon", "tiktok": None, "youtube": None},
    {"name": "Cameron Luxton", "slug": "luxton-cameron", "party": "ACT", "electorate": "List", "parliament_email": "Cameron.Luxton@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.act.org.nz/cameron-luxton", "facebook": "https://www.facebook.com/cameronluxtonact", "twitter": None, "instagram": "https://www.instagram.com/cameronluxtonact/", "tiktok": None, "youtube": None},
    {"name": "Hon Jo Luxton", "slug": "luxton-jo", "party": "Labour", "electorate": "List", "parliament_email": "Jo.Luxton@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/jo-luxton/", "facebook": "https://www.facebook.com/JoLuxtonLabour/", "twitter": "https://twitter.com/joluxx", "instagram": "https://www.instagram.com/joluxton_mp/", "tiktok": None, "youtube": None},
    {"name": "Hūhana Lyndon", "slug": "lyndon-hūhana", "party": "Green", "electorate": "List", "parliament_email": "Huhana.Lyndon@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/huhana_lyndon", "facebook": "https://www.facebook.com/hmlyndon", "twitter": None, "instagram": "https://www.instagram.com/huhana_lyndon", "tiktok": None, "youtube": None},
    {"name": "David MacLeod", "slug": "macleod-david", "party": "National", "electorate": "New Plymouth", "parliament_email": "David.MacLeod@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/davidmacleod", "facebook": "https://www.facebook.com/DavidMacleodMP/", "twitter": None, "instagram": "https://www.instagram.com/davidmacleodmp", "tiktok": None, "youtube": None},
    {"name": "Hana-Rawhiti Maipi-Clarke", "slug": "maipi-clarke-hana-rawhiti", "party": "Te Pāti Māori", "electorate": "Hauraki-Waikato", "parliament_email": "Hana-Rawhiti.Maipi-Clarke@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": None, "facebook": "https://www.facebook.com/profile.php?id=100094003368223", "twitter": None, "instagram": "https://www.instagram.com/hana_rawhiti", "tiktok": None, "youtube": None},
    {"name": "Jenny Marcroft", "slug": "marcroft-jenny", "party": "NZ First", "electorate": "List", "parliament_email": "Jenny.Marcroft@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.nzfirst.nz/jenny-marcroft", "facebook": "https://www.facebook.com/jennymarcroftmp/", "twitter": None, "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Hon Kieran McAnulty", "slug": "mcanulty-kieran", "party": "Labour", "electorate": "List", "parliament_email": "Kieran.Mcanulty@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/kieran-mcanulty/", "facebook": "https://www.facebook.com/McAnultyLabour", "twitter": "https://twitter.com/Kieran_McAnulty", "instagram": "https://www.instagram.com/kieranmcanulty", "tiktok": None, "youtube": None},
    {"name": "Grant McCallum", "slug": "mccallum-grant", "party": "National", "electorate": "Northland", "parliament_email": "Grant.McCallum@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/grantmccallum", "facebook": "https://www.facebook.com/grantmccallumnz", "twitter": None, "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Hon Todd McClay", "slug": "mcclay-todd", "party": "National", "electorate": "Rotorua", "parliament_email": "Todd.McClay@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://toddmcclay.national.org.nz", "facebook": "https://www.facebook.com/ToddMcClayMPforRotorua", "twitter": "https://twitter.com/toddmcclaymp", "instagram": "https://www.instagram.com/toddmcclay", "tiktok": None, "youtube": None},
    {"name": "Laura McClure", "slug": "trask-laura", "party": "ACT", "electorate": "List", "parliament_email": "Laura.McClure@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.act.org.nz/laura-mcclure", "facebook": "https://www.facebook.com/LauraMcClureMP/", "twitter": None, "instagram": "https://www.instagram.com/lauramcclure", "tiktok": None, "youtube": None},
    {"name": "Hon Nicole McKee", "slug": "mckee-nicole", "party": "ACT", "electorate": "List", "parliament_email": "Nicole.McKee@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.act.org.nz/nicole-mckee", "facebook": "https://www.facebook.com/nicolemckeeact", "twitter": None, "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Dr Tracey McLellan", "slug": "mclellan-tracey", "party": "Labour", "electorate": "List", "parliament_email": "Tracey.McLellan@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/tracey-mclellan/", "facebook": "https://www.facebook.com/traceymclellanlabour", "twitter": None, "instagram": "https://www.instagram.com/traceylmclellan/", "tiktok": None, "youtube": None},
    {"name": "Hon James Meager", "slug": "meager-james", "party": "National", "electorate": "Rangitata", "parliament_email": "James.MeagerMP@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/jamesmeager", "facebook": "https://www.facebook.com/JamesMeagerMP", "twitter": None, "instagram": "https://www.instagram.com/jamesmeagermp/", "tiktok": None, "youtube": None},
    {"name": "Ricardo Menéndez March", "slug": "menéndez-march-ricardo", "party": "Green", "electorate": "List", "parliament_email": "Ricardo.March@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/ricardo_menendez_march", "facebook": "https://www.facebook.com/RMMGreens", "twitter": "https://twitter.com/RMarchNZ", "instagram": "https://www.instagram.com/ricardommarch/", "tiktok": None, "youtube": None},
    {"name": "Hon Mark Mitchell", "slug": "mitchell-mark", "party": "National", "electorate": "Whangaparāoa", "parliament_email": "Mark.Mitchell@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://markmitchell.national.org.nz", "facebook": "https://www.facebook.com/markmitchellmp", "twitter": "https://twitter.com/MarkMitchellMP", "instagram": "https://www.instagram.com/markmitchellmp/", "tiktok": None, "youtube": None},
    {"name": "Joseph Mooney", "slug": "mooney-joseph", "party": "National", "electorate": "Southland", "parliament_email": "Joseph.Mooney@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://josephmooney.national.org.nz", "facebook": "https://www.facebook.com/josephmooneynz", "twitter": None, "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Rima Nakhle", "slug": "nakhle-rima", "party": "National", "electorate": "Takanini", "parliament_email": "Rima.Nakhle@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/rimanakhle", "facebook": "https://www.facebook.com/RimaNakhleTakanini", "twitter": None, "instagram": "https://www.instagram.com/rimanakhlenz", "tiktok": None, "youtube": None},
    {"name": "Debbie Ngarewa-Packer", "slug": "ngarewa-packer-debbie", "party": "Te Pāti Māori", "electorate": "Te Tai Hauāuru", "parliament_email": "Debbie.Ngarewa-Packer@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.maoriparty.org.nz/debbie_ngarewa_packer", "facebook": "https://www.facebook.com/debbiengarewapacker", "twitter": None, "instagram": "https://www.instagram.com/debbiengarewapacker/", "tiktok": None, "youtube": None},
    {"name": "Katie Nimon", "slug": "nimon-katie", "party": "National", "electorate": "Napier", "parliament_email": "Katie.Nimon@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/katienimon", "facebook": "https://www.facebook.com/KatieNimonforNapier", "twitter": None, "instagram": "https://www.instagram.com/nzkatienimon/", "tiktok": None, "youtube": None},
    {"name": "Hon Damien O'Connor", "slug": "oconnor-damien", "party": "Labour", "electorate": "List", "parliament_email": "Damien.O'Connor@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/damien-oconnor/", "facebook": "https://www.facebook.com/damienoconnormp", "twitter": "https://twitter.com/DamienOConnorMP", "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Greg O'Connor", "slug": "oconnor-greg", "party": "Labour", "electorate": "Ōhāriu", "parliament_email": "greg.o'connor@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/greg-oconnor/", "facebook": "https://www.facebook.com/GregOhariu/", "twitter": "https://twitter.com/gregohariu", "instagram": "https://www.instagram.com/gregohariu/", "tiktok": None, "youtube": None},
    {"name": "Dr Parmjeet Parmar", "slug": "parmar-parmjeet", "party": "ACT", "electorate": "List", "parliament_email": "Parmjeet.Parmar@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.act.org.nz/parmjeet-parmar", "facebook": "https://www.facebook.com/DrParmjeetParmar", "twitter": "https://x.com/Parmjeet_Parmar", "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Hon Mark Patterson", "slug": "patterson-mark", "party": "NZ First", "electorate": "List", "parliament_email": "Mark.Patterson@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://nzfirst.nz/mark-patterson", "facebook": "https://www.facebook.com/Markpatterson.nzf/", "twitter": None, "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Tamatha Paul", "slug": "paul-tamatha", "party": "Green", "electorate": "Wellington Central", "parliament_email": "Tamatha.Paul@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/tamatha_paul", "facebook": "https://www.facebook.com/tamathapaul1", "twitter": None, "instagram": "https://www.instagram.com/tamathapaul", "tiktok": None, "youtube": None},
    {"name": "Hon Chris Penk", "slug": "penk-chris", "party": "National", "electorate": "Kaipara ki Mahurangi", "parliament_email": "Chris.Penk@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://chrispenk.national.org.nz", "facebook": "https://www.facebook.com/christopherpenk/", "twitter": None, "instagram": "https://www.instagram.com/chris_penk_nz/", "tiktok": None, "youtube": None},
    {"name": "Rt Hon Winston Peters", "slug": "peters-winston", "party": "NZ First", "electorate": "List", "parliament_email": "Winston.Peters@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://nzfirst.nz/winston-peters", "facebook": "https://www.facebook.com/winstonpeters", "twitter": "https://twitter.com/winstonpeters", "instagram": "https://www.instagram.com/winstonpetersnzfirst/", "tiktok": None, "youtube": None},
    {"name": "Lan Pham", "slug": "pham-lan", "party": "Green", "electorate": "List", "parliament_email": "Lan.Pham@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/lan_pham", "facebook": "https://www.facebook.com/LanPham.nz", "twitter": None, "instagram": "https://www.instagram.com/lanpham.nz", "tiktok": None, "youtube": None},
    {"name": "Hon Tama Potaka", "slug": "potaka-tama", "party": "National", "electorate": "Hamilton West", "parliament_email": "Tama.Potaka@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/tamapotaka", "facebook": "https://www.facebook.com/TamaPotakaHamiltonWest", "twitter": None, "instagram": "https://www.instagram.com/tama_potaka/", "tiktok": None, "youtube": None},
    {"name": "Hon Willow-Jean Prime", "slug": "prime-willow-jean", "party": "Labour", "electorate": "List", "parliament_email": "Willow-Jean.Prime@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/willow-jean-prime/", "facebook": "https://www.facebook.com/willowprime/", "twitter": "https://twitter.com/willowprime", "instagram": "https://www.instagram.com/willowjeanprime/", "tiktok": None, "youtube": None},
    {"name": "Maureen Pugh", "slug": "pugh-maureen", "party": "National", "electorate": "West Coast-Tasman", "parliament_email": "Maureen.Pugh@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://maureenpugh.national.org.nz", "facebook": "https://www.facebook.com/wct.maureenpugh/", "twitter": "https://twitter.com/MaureenPughNat", "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Hon Priyanca Radhakrishnan", "slug": "radhakrishnan-priyanca", "party": "Labour", "electorate": "List", "parliament_email": "Priyanca.Radhakrishnan@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/priyanca-radhakrishnan/", "facebook": "https://www.facebook.com/priyancanzlp/", "twitter": "https://twitter.com/priyancanzlp", "instagram": "https://www.instagram.com/priyancanzlp/", "tiktok": None, "youtube": None},
    {"name": "Suze Redmayne", "slug": "redmayne-suze", "party": "National", "electorate": "Rangitīkei", "parliament_email": "Suze.Redmayne@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/suzeredmayne", "facebook": "https://www.facebook.com/suzeredmaynemp/", "twitter": None, "instagram": "https://www.instagram.com/suzeredmaynerangitikei", "tiktok": None, "youtube": None},
    {"name": "Hon Dr Shane Reti", "slug": "reti-shane", "party": "National", "electorate": "Whangārei", "parliament_email": "s.reti@ministers.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://shanereti.national.org.nz", "facebook": "https://facebook.com/DrShaneRetiMP", "twitter": "https://twitter.com/DrShaneRetiMP", "instagram": "https://instagram.com/drshaneretimp", "tiktok": None, "youtube": None},
    {"name": "Dan Rosewarne", "slug": "rosewarne-dan", "party": "Labour", "electorate": "List", "parliament_email": "Dan.Rosewarne@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://labour.org.nz/our-team/dan-rosewarne/", "facebook": "https://facebook.com/DanRosewarneWaimakariri", "twitter": None, "instagram": "https://instagram.com/waimakariridanrosewarne", "tiktok": None, "youtube": None},
    {"name": "Hon Dr Deborah Russell", "slug": "russell-deborah", "party": "Labour", "electorate": "List", "parliament_email": "Deborah.Russell@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/hon-dr-deborah-russell/", "facebook": "https://www.facebook.com/deborahrusselllabour/", "twitter": "https://twitter.com/BeeFaerie", "instagram": "https://www.instagram.com/deb_russell_mp/", "tiktok": None, "youtube": None},
    {"name": "Tom Rutherford", "slug": "rutherford-tom", "party": "National", "electorate": "Bay of Plenty", "parliament_email": "Tom.Rutherford@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/tomrutherford", "facebook": "https://www.facebook.com/TomRutherfordBOP", "twitter": None, "instagram": "https://www.instagram.com/tomrutherford_bop", "tiktok": None, "youtube": None},
    {"name": "Hon Jenny Salesa", "slug": "salesa-jenny", "party": "Labour", "electorate": "Panmure-Ōtāhuhu", "parliament_email": "Jenny.Salesa@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://labour.org.nz/our-team/hon-jenny-salesa/", "facebook": "https://facebook.com/jenny.salesa.labour", "twitter": None, "instagram": "https://instagram.com/jennysalesamp", "tiktok": None, "youtube": None},
    {"name": "Hon Carmel Sepuloni", "slug": "sepuloni-carmel", "party": "Labour", "electorate": "Kelston", "parliament_email": "Carmel.Sepuloni@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://labour.org.nz/our-team/hon-carmel-sepuloni/", "facebook": "https://facebook.com/CarmelSepuloniLabour/", "twitter": "https://twitter.com/CarmelSepuloni", "instagram": "https://instagram.com/csepuloni", "tiktok": None, "youtube": None},
    {"name": "Hon David Seymour", "slug": "seymour-david", "party": "ACT", "electorate": "Epsom", "parliament_email": "David.Seymour@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://act.org.nz/david-seymour", "facebook": "https://facebook.com/davidseymourACT", "twitter": "https://twitter.com/dbseymour", "instagram": "https://instagram.com/dbseymour", "tiktok": None, "youtube": None},
    {"name": "Hon Penny Simmonds", "slug": "simmonds-penny", "party": "National", "electorate": "Invercargill", "parliament_email": "Penny.Simmonds@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://pennysimmonds.national.org.nz", "facebook": "https://facebook.com/nzpennysimmonds", "twitter": None, "instagram": "https://instagram.com/pennysimmondsmp", "tiktok": None, "youtube": None},
    {"name": "Hon Scott Simpson", "slug": "simpson-scott", "party": "National", "electorate": "Coromandel", "parliament_email": "Scott.Simpson@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://scottsimpson.national.org.nz", "facebook": "https://facebook.com/scottsimpsonmp", "twitter": "https://twitter.com/ScottSimpsonMP", "instagram": "https://instagram.com/scottsimpsonmp", "tiktok": None, "youtube": None},
    {"name": "Stuart Smith", "slug": "smith-stuart", "party": "National", "electorate": "Kaikōura", "parliament_email": "Stuart.Smith@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://stuartsmith.national.org.nz", "facebook": "https://facebook.com/stuartsmith.national", "twitter": None, "instagram": "https://instagram.com/stuart.smithmp", "tiktok": None, "youtube": None},
    {"name": "Lemauga Lydia Sosene", "slug": "sosene-lemauga-lydia", "party": "Labour", "electorate": "Māngere", "parliament_email": "Lemauga.Lydia.Sosene@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://labour.org.nz/our-team/lemauga-lydia-sosene/", "facebook": "https://facebook.com/lemaugalydiasosenemp", "twitter": None, "instagram": "https://instagram.com/lemaugalydiasosene_mp", "tiktok": None, "youtube": None},
    {"name": "Hon Erica Stanford", "slug": "stanford-erica", "party": "National", "electorate": "East Coast Bays", "parliament_email": "Erica.Stanford@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://ericastanford.national.org.nz", "facebook": "https://facebook.com/EricaStanfordECB/", "twitter": None, "instagram": "https://instagram.com/ericastanfordecb", "tiktok": None, "youtube": None},
    {"name": "Todd Stephenson", "slug": "stephenson-todd", "party": "ACT", "electorate": "List", "parliament_email": "Todd.Stephenson@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.act.org.nz/todd-stephenson", "facebook": "https://www.facebook.com/ToddStephensonACT/", "twitter": None, "instagram": "https://www.instagram.com/toddstephenson4act/", "tiktok": None, "youtube": None},
    {"name": "Chlöe Swarbrick", "slug": "swarbrick-chloe", "party": "Green", "electorate": "Auckland Central", "parliament_email": "Chloe.Swarbrick@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/chloe_swarbrick", "facebook": "https://www.facebook.com/chloeNZgreens", "twitter": "https://twitter.com/_chloeswarbrick", "instagram": "https://www.instagram.com/chloe.swarbrick/", "tiktok": None, "youtube": None},
    {"name": "Cushla Tangaere-Manuel", "slug": "tangaere-manuel-cushla", "party": "Labour", "electorate": "Ikaroa-Rāwhiti", "parliament_email": "Cushla.Tangaere-Manuel@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://labour.org.nz/our-team/cushla-tangaere-manuel/", "facebook": "https://facebook.com/CushlaNZLabour/", "twitter": None, "instagram": "https://instagram.com/cushlatangaeremanuel", "tiktok": None, "youtube": None},
    {"name": "Hon Jan Tinetti", "slug": "tinetti-jan", "party": "Labour", "electorate": "List", "parliament_email": "Jan.Tinetti@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://labour.org.nz/our-team/jan-tinetti/", "facebook": "https://facebook.com/JanTinettiMP", "twitter": None, "instagram": "https://instagram.com/jan.tinetti", "tiktok": None, "youtube": None},
    {"name": "Teanau Tuiono", "slug": "tuiono-teanau", "party": "Green", "electorate": "List", "parliament_email": "Teanau.Tuiono@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/teanau_tuiono_mp", "facebook": "https://www.facebook.com/TeanauTalks", "twitter": None, "instagram": "https://www.instagram.com/teanau_tuiono", "tiktok": None, "youtube": None},
    {"name": "Hon Phil Twyford", "slug": "twyford-phil", "party": "Labour", "electorate": "Te Atatū", "parliament_email": "Phil.Twyford@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://labour.org.nz/our-team/phil-twyford/", "facebook": "https://facebook.com/phil.twyford.mp", "twitter": None, "instagram": "https://instagram.com/twyford.phil", "tiktok": None, "youtube": None},
    {"name": "Sam Uffindell", "slug": "uffindell-sam", "party": "National", "electorate": "Tauranga", "parliament_email": "Sam.Uffindell@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://samuffindell.national.org.nz", "facebook": "https://facebook.com/SamUffindellTauranga/", "twitter": None, "instagram": "https://instagram.com/samuffindelltauranga", "tiktok": None, "youtube": None},
    {"name": "Hon Louise Upston", "slug": "upston-louise", "party": "National", "electorate": "Taupō", "parliament_email": "Louise.Upston@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://louiseupston.national.org.nz", "facebook": "https://facebook.com/louiseupstonmp/", "twitter": None, "instagram": "https://instagram.com/upstonl", "tiktok": None, "youtube": None},
    {"name": "Tangi Utikere", "slug": "utikere-tangi", "party": "Labour", "electorate": "Palmerston North", "parliament_email": "Tangi.Utikere@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://labour.org.nz/our-team/tangi-utikere/", "facebook": "https://facebook.com/tangi.utikere.nz", "twitter": None, "instagram": "https://instagram.com/tangiutikere", "tiktok": None, "youtube": None},
    {"name": "Tim van de Molen", "slug": "van-de-molen-tim", "party": "National", "electorate": "Waikato", "parliament_email": "Tim.vandemolen@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://timvandemolen.national.org.nz/", "facebook": "https://www.facebook.com/TimvandeMolenWaikato/", "twitter": None, "instagram": "https://www.instagram.com/timvandemolenmp/", "tiktok": None, "youtube": None},
    {"name": "Hon Brooke van Velden", "slug": "van-velden-brooke", "party": "ACT", "electorate": "Tāmaki", "parliament_email": "Brooke.Vanvelden@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.act.org.nz/brooke-van-velden", "facebook": "https://www.facebook.com/brookevanveldenmp/", "twitter": "https://twitter.com/BrookevanVelden", "instagram": "https://www.instagram.com/brookevanvelden/", "tiktok": None, "youtube": None},
    {"name": "Hon Dr Ayesha Verrall", "slug": "verrall-ayesha", "party": "Labour", "electorate": "List", "parliament_email": "Ayesha.Verrall@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/ayesha-verrall/", "facebook": "https://www.facebook.com/drayeshaverrall/", "twitter": "https://twitter.com/drayeshaverrall", "instagram": "https://www.instagram.com/drayeshaverrallmp", "tiktok": None, "youtube": None},
    {"name": "Celia Wade-Brown", "slug": "wade-brown-celia", "party": "Green", "electorate": "List", "parliament_email": "Celia.Wade-Brown@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/", "facebook": "https://www.facebook.com/celia.wadebrown/", "twitter": None, "instagram": "https://www.instagram.com/celiawb/", "tiktok": None, "youtube": None},
    {"name": "Rawiri Waititi", "slug": "waititi-rawiri", "party": "Te Pāti Māori", "electorate": "Waiariki", "parliament_email": "Rawiri.Waititi@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.maoriparty.org.nz/rawiri_waititi", "facebook": "https://www.facebook.com/RawiriWaititiMP", "twitter": "https://twitter.com/Rawiri_Waititi", "instagram": "https://www.instagram.com/rawiri_waititi/", "tiktok": None, "youtube": None},
    {"name": "Vanushi Walters", "slug": "walters-vanushi", "party": "Labour", "electorate": "List", "parliament_email": "Vanushi.Walters@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/vanushi-walters/", "facebook": "https://www.facebook.com/VanushiSWalters/", "twitter": None, "instagram": "https://www.instagram.com/vanushiwalters/", "tiktok": None, "youtube": None},
    {"name": "Hon Simon Watts", "slug": "watts-simon", "party": "National", "electorate": "North Shore", "parliament_email": "Simon.Watts@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://simonwatts.national.org.nz/", "facebook": "https://www.facebook.com/simonwattsmp", "twitter": None, "instagram": "https://www.instagram.com/simonwattsmp/", "tiktok": None, "youtube": None},
    {"name": "Hon Dr Duncan Webb", "slug": "webb-duncan", "party": "Labour", "electorate": "Christchurch Central", "parliament_email": "Duncan.Webb@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/hon-dr-duncan-webb/", "facebook": "https://www.facebook.com/DuncanWebbLabour", "twitter": None, "instagram": "https://www.instagram.com/duncanwebbmp/", "tiktok": None, "youtube": None},
    {"name": "Catherine Wedd", "slug": "wedd-catherine", "party": "National", "electorate": "Tukituki", "parliament_email": "Catherine.Wedd@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/catherinewedd", "facebook": "https://www.facebook.com/catherineweddfortukituki", "twitter": None, "instagram": "https://www.instagram.com/nzcatherinewedd/", "tiktok": None, "youtube": None},
    {"name": "Dr Vanessa Weenink", "slug": "weenink-vanessa", "party": "National", "electorate": "Banks Peninsula", "parliament_email": "Vanessa.Weenink@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/vanessaweenink", "facebook": "https://www.facebook.com/VanessaWeeninkBanksPeninsula", "twitter": None, "instagram": "https://www.instagram.com/vanessaweeninkbankspeninsulamp/", "tiktok": None, "youtube": None},
    {"name": "Helen White", "slug": "white-helen", "party": "Labour", "electorate": "Mt Albert", "parliament_email": "Helen.White@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/helen-white/", "facebook": "https://www.facebook.com/HelenWhiteLabour/", "twitter": None, "instagram": "https://www.instagram.com/helen_white_labour/", "tiktok": None, "youtube": None},
    {"name": "Arena Williams", "slug": "williams-arena", "party": "Labour", "electorate": "Manurewa", "parliament_email": "Arena.Williams@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/arena-williams/", "facebook": "https://www.facebook.com/ArenaWilliamsManurewa", "twitter": None, "instagram": "https://www.instagram.com/arenawilliams", "tiktok": None, "youtube": None},
    {"name": "Hon Nicola Willis", "slug": "willis-nicola", "party": "National", "electorate": "List", "parliament_email": "Nicola.Willis@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.national.org.nz/team/nicolawillis", "facebook": "https://www.facebook.com/NicolaWillisMP/", "twitter": "https://x.com/NicolaWillisMP", "instagram": "https://www.instagram.com/nicolawillismp/", "tiktok": None, "youtube": None},
    {"name": "Scott Willis", "slug": "willis-scott", "party": "Green", "electorate": "List", "parliament_email": "Scott.Willis@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/scott_willis", "facebook": "https://www.facebook.com/ScottWillisforTaieri", "twitter": None, "instagram": "https://www.instagram.com/scottwillisnz", "tiktok": None, "youtube": None},
    {"name": "Dr David Wilson", "slug": "wilson-david", "party": "NZ First", "electorate": "List", "parliament_email": "David.WilsonMP@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.nzfirst.nz/david-wilson", "facebook": "https://www.facebook.com/davidwilsonnzfirst/", "twitter": None, "instagram": None, "tiktok": None, "youtube": None},
    {"name": "Hon Dr Megan Woods", "slug": "woods-megan", "party": "Labour", "electorate": "Wigram", "parliament_email": "Megan.Woods@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.labour.org.nz/our-team/megan-woods/", "facebook": "https://www.facebook.com/MeganWoodsWigram/", "twitter": "https://twitter.com/Megan_Woods", "instagram": "https://www.instagram.com/megancwoods/", "tiktok": None, "youtube": None},
    {"name": "Dr Lawrence Xu-Nan", "slug": "xu-nan-lawrence", "party": "Green", "electorate": "List", "parliament_email": "Lawrence.Xu-Nan@parliament.govt.nz", "parliament_phone_nz": "0800 7273 6282", "parliament_phone_intl": "+64 4 817 9999", "postal_address": "Private Bag 18888, Parliament Buildings, Wellington 6160", "website": "https://www.greens.org.nz/lawrence_xu_nan", "facebook": "https://www.facebook.com/lawrence.xunan/", "twitter": "https://twitter.com/lx_xunan", "instagram": "https://www.instagram.com/lawrence_xunan/", "tiktok": None, "youtube": None},
]

# Map MP slug → image filename in bees/ folder.
# Built by inspecting bees/ filenames and matching to MP names.
# Some images are intentionally unmatched (former MPs or unclear identity).
SLUG_TO_IMAGE = {
    "abel-steve": "abel-steve.jpg",
    "andersen-ginny": "andersen-virginia.jpg",  # Virginia is Ginny's full name
    "anderson-miles": "anderson-miles.jpg",
    "arbuckle-jamie": "arbuckle-jamie.jpg",
    "bates-carl": "bates-carl.jpg",
    "bayly-andrew": "andrew-bayly-official-photo-green-background-1.jpeg",
    "belich-camilla": "belich-camilla.jpg",
    "bennett-glen": "bennett-glen.jpg",
    "bidois-dan": "bidois-dan.jpg",
    "bishop-chris": "bishop-chris.jpg",
    "boyack-rachel": "boyack.png",
    "brewer-cameron": "brewer-cameron.jpg",
    "brooking-rachel": "brooking-rachel-va2877757.jpg",
    "brown-simeon": "simeon-brown.jpg",
    "brownlee-gerry": "brownlee-gerry3.jpg",
    "butterick-mike": "edited-mike-headshot-2023.jpg",  # likely Mike Butterick (joined Oct 2023)
    "cameron-mark": "cameron-mark.jpg",
    "campbell-hamish": "campbell-hamish.jpg",
    "carter-kahurangi": "kahurangi-carter.jpg",
    "cheung-carlos": "cheung-carlos.jpg",
    "chhour-karen": "chhour-karen.jpg",
    "costello-casey": "costello-casey.jpg",
    "costley-tim": "costley-tim.jpg",
    "court-simon": "court-simon.jpg",
    # "dansey-georgie": NO IMAGE
    "davidson-marama": "davidson-marama.jpg",
    # "davidson-mike": NO IMAGE (edited-mike-headshot used for Butterick)
    "davidson-reuben": "davidson-reuben.jpg",
    "doocey-matt": "doocey-matt.jpg",
    "edmonds-barbara": "edmonds-barbara.jpg",
    "ferris-tākuta": "tākuta-ferris.jpg",
    "fleming-greg": "fleming-greg.jpg",
    "foster-andy": "andy-foster.jpg",
    "garcia-paulo": "garcia-paulo.jpg",
    "genter-julie-anne": "genter-julie-anne.jpg",
    "goldsmith-paul": "goldsmith-paul5.jpg",
    "grigg-nicola": "grigg-nicola.jpg",
    "halbert-shanan": "halbert-shanan.jpg",
    "hamilton-ryan": "hamilton-ryan.jpg",
    "hernandez-francisco": "hernandez-francisco.jpeg",
    "hipkins-chris": "chris-hipkins.jpg",
    "hoggard-andrew": "andrew-hoggard.jpg",
    "jackson-willie": "jackson-willie.jpg",
    "jones-shane": "shane-jones.png",
    # "kaipara-oriini": NO IMAGE
    # "kapa-kingi-mariameno": NO IMAGE
    "kirkpatrick-dana": "dana.jpg",
    # "kuriger-barbara": NO IMAGE
    "leary-ingrid": "ingrid-leary_red_right_cropped.jpg",
    "lee-melissa": "lee-melissa.jpg",
    "lu-nancy": "nancy-lu.jpeg",
    "luxon-christopher": "luxon-chris.jpg",
    "luxton-cameron": "luxton-cameron.jpg",
    "luxton-jo": "edited-jo-luxton-portrait_2023.jpg",
    "lyndon-hūhana": "lyndon-hūhana.jpg",
    "macleod-david": "macleod-david.jpg",
    "maipi-clarke-hana-rawhiti": "maipi-clarke-hana-rawhiti.jpg",
    "marcroft-jenny": "marcroft-jenny.jpg",
    "mcanulty-kieran": "mcanulty-kieran.jpg",
    "mccallum-grant": "mccallum-grant.jpg",
    "mcclay-todd": "mcclay-todd.jpg",
    "trask-laura": "trask-laura.jpg",  # Laura McClure, formerly Trask
    "mckee-nicole": "cropped-nicole-mckee-photo2-2.jpg",
    "mclellan-tracey": "mclellan-tracey.jpg",
    "meager-james": "meager-james.jpeg",
    "menéndez-march-ricardo": "march-ricardo.jpg",
    "mitchell-mark": "mitchell-mark.jpg",
    "mooney-joseph": "mooney-joseph.jpg",
    "nakhle-rima": "nikahle-rima.jpg",  # filename typo of Nakhle
    "ngarewa-packer-debbie": "ngarewa-packer-debbie.jpg",
    "nimon-katie": "nimon-katie.jpg",
    "oconnor-damien": "oconnor-damien.jpg",
    "oconnor-greg": "oconnor-greg.jpg",
    "parmar-parmjeet": "parmar-parmjeet.jpg",
    "patterson-mark": "patterson-mark-2.jpg",
    "paul-tamatha": "paul-tamatha.jpg",
    "penk-chris": "penk-chris.jpg",
    "peters-winston": "peters-winston.jpg",
    "pham-lan": "pham-lan.jpg",
    "potaka-tama": "potaka-tama.jpg",
    "prime-willow-jean": "prime-willow-jean.jpg",
    "pugh-maureen": "pugh-maureen.jpg",
    "radhakrishnan-priyanca": "radhakrishnan-priyanca.jpeg",
    "redmayne-suze": "redmayne-suze.jpg",
    "reti-shane": "reti-shane.jpg",
    # "rosewarne-dan": NO IMAGE
    "russell-deborah": "russell-deborah.jpg",
    "rutherford-tom": "rutherford-tom.jpg",
    "salesa-jenny": "salesa-jenny.jpg",
    "sepuloni-carmel": "sepuloni-carmel.jpg",
    "seymour-david": "seymour-david.jpg",
    "simmonds-penny": "simmonds-penny.jpg",
    "simpson-scott": "simpson-scott.jpg",
    "smith-stuart": "smith-stuart.jpg",
    "sosene-lemauga-lydia": "lemauga.jpg",
    "stanford-erica": "erica-stanford.jpg",
    "stephenson-todd": "stephenson-todd.jpg",
    "swarbrick-chloe": "swarbrick-chloe.jpg",
    "tangaere-manuel-cushla": "Tangaere-Manuel, Cushla.jpg",
    "tinetti-jan": "tinetti-jan.jpg",
    "tuiono-teanau": "tuiono-teanau.jpg",
    "twyford-phil": "twyford-phil.jpg",
    "uffindell-sam": "uffindell-sam.jpg",
    "upston-louise": "upston-louise.jpg",
    "utikere-tangi": "tangi-utikere.jpg",
    "van-de-molen-tim": "van-de-molen-tim.jpg",
    "van-velden-brooke": "van-velden-brooke.jpg",
    "verrall-ayesha": "verrall-ayesha.jpg",
    "wade-brown-celia": "wade-brown-celia.jpg",
    "waititi-rawiri": "waititi-rawiri.jpg",
    "walters-vanushi": "walters-vanushi.jpg",
    "watts-simon": "watts-simon.jpg",
    "webb-duncan": "webb-duncan.jpg",
    "wedd-catherine": "wedd-catherine.jpeg",
    "weenink-vanessa": "weenink-vanessa.jpg",
    "white-helen": "white-helen.jpg",
    "williams-arena": "williams-arena.jpg",
    "willis-nicola": "willis-nicola.jpg",
    "willis-scott": "willis-scott.jpg",
    "wilson-david": "david-wilson-mp-2.jpg",
    "woods-megan": "megan-woods-profile-780-002.jpg",
    "xu-nan-lawrence": "xu-lawrence.jpg",
}

BEES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "bees")
OUTPUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mps.json")

# Verify every mapped image actually exists in bees/
existing_files = set(os.listdir(BEES_DIR))
mapped_files = set(SLUG_TO_IMAGE.values())

missing_on_disk = [f for f in mapped_files if f not in existing_files]
if missing_on_disk:
    print("WARNING: these mapped images do not exist on disk:")
    for f in missing_on_disk:
        print(f"  {f}")

# Build the output records
records = []
for mp in MPS:
    image_filename = SLUG_TO_IMAGE.get(mp["slug"])
    record = {
        "name": mp["name"],
        "slug": mp["slug"],
        "party": mp["party"],
        "electorate": mp["electorate"],
        "image": f"bees/{image_filename}" if image_filename else None,
        "profile_url": f"https://www3.parliament.nz/en/mps-and-electorates/members-of-parliament/{mp['slug']}/",
        "parliament_email": mp["parliament_email"],
        "parliament_phone_nz": mp["parliament_phone_nz"],
        "parliament_phone_intl": mp["parliament_phone_intl"],
        "postal_address": mp["postal_address"],
        "website": mp["website"],
        "facebook": mp["facebook"],
        "twitter": mp["twitter"],
        "instagram": mp["instagram"],
        "tiktok": mp["tiktok"],
        "youtube": mp["youtube"],
    }
    records.append(record)

mps_with_image = [r for r in records if r["image"]]
mps_without_image = [r["name"] for r in records if not r["image"]]
unused_images = sorted(existing_files - mapped_files)

output = {
    "scraped_at": "2026-06-22",
    "source": "https://www3.parliament.nz/en/mps-and-electorates/members-of-parliament/",
    "count": len(records),
    "count_with_image": len(mps_with_image),
    "mps_without_image": mps_without_image,
    "unused_images_in_bees_folder": unused_images,
    "mps": records,
}

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print(f"\nWrote {len(records)} MPs to {OUTPUT_PATH}")
print(f"  With image: {len(mps_with_image)}")
print(f"  Without image: {len(mps_without_image)}")
print(f"  Unused images in bees/: {len(unused_images)}")
if mps_without_image:
    print("\nMPs without image:")
    for n in mps_without_image:
        print(f"  - {n}")
if unused_images:
    print("\nUnused images in bees/ folder (likely former MPs):")
    for f in unused_images:
        print(f"  - {f}")
